apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'telegram'
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h

    receivers:
    - name: 'telegram'
      telegram_configs:
      - bot_token_file: '/etc/secrets/bot-token'
        chat_id: 1453814397
        parse_mode: 'HTML'
        message: |
          {{ range .Alerts }}
          <b>🔔 {{ .Labels.severity | toUpper }}</b>
          
          <b>Alert:</b> {{ .Labels.alertname }}
          <b>Service:</b> {{ .Labels.service }}
          <b>Instance:</b> {{ .Labels.instance }}
          
          <b>Description:</b> {{ .Annotations.description }}
          
          <b>Status:</b> {{ .Status }}
          {{ if eq .Status "firing" }}🔴{{ else }}✅{{ end }}
          {{ end }}