apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: service-checker

images:
  - name: ghcr.io/miracleqxz/k8s-flask-app
    newTag: latest

commonLabels:
  environment: production
