apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-worker
  namespace: service-checker
  labels:
    app: analytics-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-worker
  template:
    metadata:
      labels:
        app: analytics-worker
    spec:
      containers:
      - name: analytics-worker
        image: ghcr.io/miracleqxz/k8s-flask-app:latest
        imagePullPolicy: Always
        command: ["python", "analytics_worker.py"]
        env:
        - name: ENV
          value: "production"
        - name: POSTGRES_HOST
          value: "postgres.service-checker.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: RABBITMQ_HOST
          value: "rabbitmq.service-checker.svc.cluster.local"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
