apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
spec:
  project: service-checker
  
  source:
    repoURL: https://github.com/miracleqxz/k8s-Flask-app.git
    targetRevision: main
    path: apps/alertmanager/overlays/production
  
  destination:
    server: https://kubernetes.default.svc
    namespace: service-checker
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m