apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml

namespace: service-checker

labels:
  - pairs:
      app: rabbitmq
      component: messaging
      managed-by: argocd