apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

namespace: service-checker

labels:
  - pairs:
      app: analytics-worker
      component: worker
      managed-by: argocd